const mealKits = [
  {
    id: 1,
    name: "Garlic Bread",
    time: 30,
    category: "Breakfast",
    img: "./assets/imgs/garlic-bread.jpg",
    price: 250,
    discount: 20,
  },
  {
    id: 2,
    name: "Cheesecake With Kiwi & Cherry",
    time: 30,
    category: "Dessert",
    img: "./assets/imgs/cheesecake-with-slice-kiwi-glazed-cherry-caramelized-sugar.jpg",
    price: 320,
  },
  {
    id: 3,
    name: "Chicken Alfredo",
    time: 40,
    category: "Chicken",
    img: "./assets/imgs/chicken-alfredo-1.jpg",
    price: 450,
    discount: 10,
  },
  {
    id: 4,
    name: "Chicken Taco Casserole",
    time: 30,
    category: "Chicken",
    img: "./assets/imgs/chicken-taco-casserole-1.jpg",
    price: 370,
  },
  {
    id: 5,
    name: "Grilled Beef Steak",
    time: 45,
    category: "Meat",
    img: "./assets/imgs/grilled-beef-steak-served-with-green-salad-with-eggs.jpg",
    price: 550,
    discount: 15,
  },
  {
    id: 6,
    name: "Roast Chicken With Potatoes",
    time: 40,
    category: "Chicken",
    img: "./assets/imgs/chicken-dish.jpg",
    price: 420,
  },
  {
    id: 7,
    name: "Italian Meatballs",
    time: 40,
    category: "Meat",
    img: "./assets/imgs/Italian-meatballs-3.jpg",
    price: 390,
  },
  {
    id: 8,
    name: "Cast Iron Skillet Pizza",
    time: 30,
    category: "Lunch",
    img: "./assets/imgs/pizza.jpg",
    price: 300,
    discount: 5,
  },
  {
    id: 9,
    name: "Smoked Wings",
    time: 30,
    category: "Lunch",
    img: "./assets/imgs/smoked-wings-1.jpg",
    price: 280,
  },
  {
    id: 10,
    name: "Koshari",
    time: 25,
    category: "Egyptian",
    img: "./assets/imgs/koshari.jpg",
    price: 180,
    discount: 10,
  },
  {
    id: 11,
    name: "Molokhia with Rice & Chicken",
    time: 35,
    category: "Egyptian",
    img: "./assets/imgs/molokhia.jpg",
    price: 350,
  },
  {
    id: 12,
    name: "Stuffed Vine Leaves (Warak Enab)",
    time: 50,
    category: "Egyptian",
    img: "./assets/imgs/warak-enab.jpg",
    price: 400,
    discount: 15,
  },
];
